NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.buy1.jpeg.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.buy1.jpeg.com-cert.pem
    OrganizationalUnitIdentifier: peer
